

export const LOAD_DEPARTURES = 'scandlines/LOAD_DEPARTURES'
export const DEPARTURES_PAYLOAD_PROCESSED = 'scandlines/DEPARTURES_PAYLOAD_PROCESSED'
export const DEPARTURES_ALL_LOADED = 'scandlines/DEPARTURES_ALL_LOADED'
export const LOAD_DEPARTURES_ERROR = 'scandlines/LOAD_DEPARTURES_ERROR'
export const DEPARTURES_BATCH_LOADED = 'scandlines/DEPARTURES_BATCH_LOADED'
export const ERASE_DEPARTURES= 'scandlines/ERASE_DEPARTURES'